### ISSUE TITLE
Can't preview clips, snapshots

### ISSUE THREAD

**Issue by Davidvm86** [blakeblackshear/frigate#1534]
When using the webui I can't view, I can only preview in the media browser local media but I can't preview in the media browser frigate.

When inspecting the browser is found 2 difference.
This does not work:
Shows thumbnails in the media browser.

https://hostname/api/frigate/frigate/clips/Voordeur-1629173719.462282-248fd1.mp4?authSig=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjNjA4YmI1NDI0NTg0NzdkYjQwMDg4YTVkYzFlYzhjOSIsInBhdGgiOiIvYXBpL2ZyaWdhdGUvZnJpZ2F0ZS9jbGlwcy9Wb29yZGV1ci0xNjI5MTczNzE5LjQ2MjI4Mi0yNDhmZDEubXA0IiwiaWF0IjoxNjI5MTc4MDAzLCJleHAiOjE2MjkyNjQ0MDN9.Fj167YJh2Y3QXRlT1eMEET6OqTqHezYbRwKlGcWf_DM

This does work:
Does not show thumbnails in the media browser.

https://hostname/media/local/frigate/clips/Voordeur-1629173719.462282-248fd1.mp4?authSig=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjNjA4YmI1NDI0NTg0NzdkYjQwMDg4YTVkYzFlYzhjOSIsInBhdGgiOiIvYXBpL2ZyaWdhdGUvZnJpZ2F0ZS9jbGlwcy9Wb29yZGV1ci0xNjI5MTczNzE5LjQ2MjI4Mi0yNDhmZDEubXA0IiwiaWF0IjoxNjI5MTc4MDAzLCJleHAiOjE2MjkyNjQ0MDN9.Fj167YJh2Y3QXRlT1eMEET6OqTqHezYbRwKlGcWf_DM

detectors:
  coral:
    type: cpu

mqtt:
  host: hostname
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: 
  password: 
  stats_interval: 60

cameras:
  Voordeur:
    ffmpeg:
      inputs:
        - path: rtsp://user:password@hostname:8557/mpeg/720p/media.amp
          roles:
            - detect
            - rtmp
            - clips
            - record
    width: 1280
    height: 720
    fps: 12

**Screenshots**

**Computer Hardware**
 - OS: Synology
 - Install method: Hass OS
 - Virtualization: Synology virtual manager
 - Network Setup: Wired

**Comment by blakeblackshear** [comment]
What version are you running?

**Comment by Davidvm86** [comment]
> What version are you running?

Frigate 1.13 Update to 0.8.4

core-2021.8.7
Home Assistant OS 6.2
supervisor-2021.06.8

**Comment by blakeblackshear** [comment]
Can you view the clips in the WebUI for frigate?

**Comment by Davidvm86** [comment]
> Can you view the clips in the WebUI for frigate?

No I can't when selecting them play button won't do anything.
<img width="443" alt="Screenshot 2021-08-17 at 13 32 49" src="https://user-images.githubusercontent.com/72596931/129718799-cebad4d5-60b1-4491-8434-073119848056.png">

**Comment by blakeblackshear** [comment]
Can you check for errors in the browser console? In Chrome, you would right click on the page and click inspect.

**Comment by Davidvm86** [comment]
> Can you check for errors in the browser console? In Chrome, you would right click on the page and click inspect.

found this as een error:
Voordeur-1629173719.462282-248fd1.mp4:1 Failed to load resource: the server responded with a status of 403 ()

**Comment by blakeblackshear** [comment]
This happens when nginx does not have the execute permission on the `/media/frigate` folder. Can you provide some information on how you have setup storage for HassOS on the synology?

**Comment by Davidvm86** [comment]
> This happens when nginx does not have the execute permission on the `/media/frigate` folder. Can you provide some information on how you have setup storage for HassOS on the synology?

I Have setup the Home assistant in the Virtual manager of the Synology.

in my config.yaml I got following 

default_config:
media_source:

I did not change anything else after installing the frigate package and add-on

**Comment by blakeblackshear** [comment]
You may want to try asking here: https://github.com/blakeblackshear/frigate/discussions/1047

**Comment by Davidvm86** [comment]
Fixed by permission change op the /media folder

**Comment by janstadt** [comment]
Im getting the 403 as well. Right now i have it mapped to a specific location on my nas but its not allowing me to view clips via media browser. You changed the permission for the /media directory on host or inside the container?

**Comment by janstadt** [comment]
I did an entire rebuild of the container and noticed that with this configuration that the /media/frigate folder inside the container is owned by `root:users` whereas everything within the folder (clips/recordings/etc all recurisvely) have an owner of `root:root`. If i chown the frigate folder inside the container to `root:root` i dont seen ay change in functionality and i still cannot view the media in the browser (chrome). 

This is all running on a qnap nas via container station.

Here's my docker-compose portion for frigate.
```
frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-amd64
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/frigate/frigate.yml:/config/config.yml:ro //ROOT is /share/docker/HTPC
      - ${ROOT_PARENT}/media/frigate:/media/frigate //ROOT_PARENT /share/docker
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: ${FRIGATE_RTSP_PASSWORD}
      FRIGATE_MQTT_PASSWORD: ${FRIGATE_MQTT_PASSWORD}
```
frigate.yml
```
ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  global_args: -hide_banner -loglevel warning
  # Optional: global hwaccel args (default: shown below)
  # NOTE: See hardware acceleration docs for your specific device
  hwaccel_args:
    - -hwaccel
    - qsv
    - -qsv_device
    - /dev/dri/renderD128
  # Optional: global output args
  #output_args:
  #  clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -c:a aac -filter:a volume=1.5
  output_args:
    # Optional: output args for detect streams (default: shown below)
    detect: -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -c:a aac
    # Optional: output args for clips streams (default: shown below)
    clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -c:a aac
    # Optional: output args for rtmp streams (default: shown below)
    rtmp: -c copy -f flv
detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu
  cpu4:
    type: cpu
mqtt: 
  host: 192.168.1.89
  password: '{FRIGATE_MQTT_PASSWORD}'
  user: mqttuser
cameras: 
  porch: 
    ffmpeg: 
      inputs: 
        - 
          path: 'rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.195:554/cam/realmonitor?channel=1&subtype=1'
          roles: 
            - detect
            - rtmp
        - 
          path: 'rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.195:554/cam/realmonitor?channel=1&subtype=0'
          roles: 
            - clips
            - record
    fps: 5
    height: 480
    width: 640
    motion:
      mask:
        - 0,480,0,356,242,258,323,342,321,402,219,480
        - 431,0,428,90,199,79,87,102,67,37
        - 549,116,517,236,469,308,378,433,312,392,430,71
        - 601,263,570,349,516,325,538,252
    objects:
      track:
        - person
      mask:
        - 0,480,0,356,242,258,323,342,321,402,219,480
        - 431,0,428,90,199,79,87,102,67,37
        - 549,116,517,236,469,308,378,433,312,392,430,71
        - 601,263,570,349,516,325,538,252
    clips:
      enabled: true
      objects:
        - person
      retain: 
        default: 10
        objects: 
          person: 15
  deck: 
    ffmpeg: 
      inputs: 
        - 
          path: 'rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.196:554/cam/realmonitor?channel=1&subtype=1'
          roles: 
            - detect
            - rtmp
        - 
          path: 'rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.196:554/cam/realmonitor?channel=1&subtype=0'
          roles: 
            - clips
            - record
    fps: 5
    height: 480
    width: 640
    motion:
      mask:
        - 0,0,226,0,229,25,133,40,153,118,0,149
        - 468,0,414,96,383,77,392,0
        - 552,0,640,57,611,121,431,0
    objects:
      track:
        - person
      mask:
        - 0,0,226,0,229,25,133,40,153,118,0,149
        - 468,0,414,96,383,77,392,0
        - 552,0,640,57,611,121,431,0
    clips:
      enabled: true
      objects:
        - person
      retain: 
        default: 10
        objects: 
          person: 15
objects: 
  filters: 
    person: 
      max_area: 100000
      min_area: 5000
      min_score: 0.5
      threshold: 0.7
  track: 
    - person
record: 
  enabled: true
  retain_days: 7
clips:
  max_seconds: 300
  # Optional: size of tmpfs mount to create for cache files (default: not set)
  # mount -t tmpfs -o size={tmpfs_cache_size} tmpfs /tmp/cache
  # NOTICE: Addon users must have Protection mode disabled for the addon when using this setting.
  # Also, if you have mounted a tmpfs volume through docker, this value should not be set in your config.
  #tmpfs_cache_size: 256m
  # Optional: Retention settings for clips (default: shown below)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 15
```

**Comment by blakeblackshear** [comment]
You need to make sure execute is permitted on the directory for nginx to serve files.

**Comment by janstadt** [comment]
Thanks for the response @blakeblackshear . Im seeing `drwxrwxrwx` on the parent folder and the 2 folders that are created (clips and recordings). I also noticed that `/share/media` was symlink that pointed to `CACHEDEV1_DATA/media/` but both the symlink and the folder have the same permissions outside of `l` and `d` for each type of file. Do the actual mp4 files need to also have execute permissions on it as well? They are showing `-rw-rw----` which i guess makes sense. I gotta have something messed up here. I had playback and recording and everything working INSIDE the VM via the addon but then i started thinking about how things could get messy passing the coral usb through to the VM since it only supports usb2. I then installed via docker directly and i can see the live view but just not the recorded stuff.

**Comment by blakeblackshear** [comment]
You could look at the error logs for nginx inside the container to see if it's something else. Should be at /var/log/nginx/error.log in the container.

**Comment by janstadt** [comment]
Definitely a permission issue. Just not sure what or why it would be messed up. Nginx executes as root right? Does the folder and parent folder need to be owned by root on the host?

**Comment by scooper1** [comment]
if you work this error out please post fix here as got the same problem I will do likewise if I manage to fix

**Comment by janstadt** [comment]
If i enter the frigate container and inspect the `/media/frigate` folder and its contents i noticed that its perms looked a bit different. It has a + at the end like `drwxrwxrwx+` which i think means there are additional access controls (ACLs) on the folders. Could this be it or is this by design @blakeblackshear ?

**Comment by blakeblackshear** [comment]
There are no special permissions set by frigate by design.

**Comment by janstadt** [comment]
I installed acl and this is the output of `getfacl` for the /frigate folder:
```
root@8c81ba55e625:/media# getfacl frigate/
# file: frigate/
# owner: root
# group: root
user::rwx
user:1000:rwx
user:1001:rwx
user:nobody:---
group::rwx
group:root:rwx
mask::rwx
other::rwx
default:user::rwx
default:user:1000:rwx
default:user:1001:rwx
default:user:nobody:---
default:group::rwx
default:group:root:rwx
default:mask::rwx
default:other::---
```

**Comment by blakeblackshear** [comment]
Did you already try running `chmod +x` on all the directories in the /media directory from within the container?

**Comment by janstadt** [comment]
Sorry for all the spam here. I rebuilt the container and set it to a different folder in qnap (/share/recordings/frigate:/media/frigate) and upon creation the frigate folder that wasnt in the recordings directory was created: `drwxr-xr-x  4 admin administrators 4096 2021-08-19 22:06 frigate`. 
Inside the frigate folder the clips and recordings directories show:
```
drwxrwxrwx 2 admin administrators 4096 2021-08-19 22:10 clips
drwxrwxrwx 3 admin administrators 4096 2021-08-19 22:10 recordings
```
Not sure if this is helpful or not. I'll try running `chmod +x` in the container and see how she goes.

**Comment by janstadt** [comment]
`chomd -R +x media/` didnt help. I did notice that clips and recordings are set to allow to be written by others but the parent folder isnt so i did `chmod -R 777 frigate/` but that also didnt do anything. Calling it a night here.

**Comment by janstadt** [comment]
Alright i think i figured it out. It is indeed due to ACLs that qnap/synology add onto the folders. I found these two articles here and the key was to add `user root;` to my nginx.conf inside the container. I now can view the clips!

https://forums.docker.com/t/nginx-403-forbidden/99953
https://forum.qnap.com/viewtopic.php?t=142850

I did try passing `:Z` along through the volume as well as use the `${PWD}` var inside my docker-compose but that didnt work.

@blakeblackshear do you know if this will be ok to change or will it affect other permissioning or if nginx is suppose to run as some other user? Just dont want to break anything downstream.

**Comment by blakeblackshear** [comment]
Should be fine. Thanks for hunting it down. I may consider adding that change directly if this becomes common.

**Comment by scooper1** [comment]
fixed mine by logging into the docker image and doing a chmod 777 on the media frigate directory

**Comment by CodingSquirrel** [comment]
> 
> 
> Should be fine. Thanks for hunting it down. I may consider adding that change directly if this becomes common.

I ran into this issue as well and think changing nginx to run as the same user as the base program makes more sense, especially considering configuring permissions. I spent a bit of time tonight troubleshooting why it runs as and can write with only root permissions, but cannot display snapshots or video without 755 permissions. Since this is for security footage and my host is used for other purposes as well I prefer to keep the files 700 and give specific permissions over ACL, instead of giving wide read access.
