### ISSUE TITLE
Supervisor 2021.02.1 seams breaking the Addon

### ISSUE THREAD

**Issue by thundergreen** [blakeblackshear/frigate#703]
Dear @blakeblackshear thanks a lot for this awesome addon and customcomponent. It was runing like a charm. Unfortunately I face an isse after upgrading my supervisor (supervised install method of Home assistant).

Now each time I want to save my config I geet this error (Chrome console):

```
chunk.97b95a62afbc18471344.js:3350 Uncaught (in promise) TypeError: Cannot read property 'find' of null
    at HTMLElement.value (chunk.97b95a62afbc18471344.js:3350)
    at HTMLElement.performUpdate (entrypoint.cf81f6d9.js:35547)
    at HTMLElement._enqueueUpdate (entrypoint.cf81f6d9.js:35547)
```
```
Could not load content for webpack://home-assistant-frontend/chunk.97b95a62afbc18471344.js (HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME)
```
![image](https://user-images.githubusercontent.com/13320319/106751325-50c96400-6629-11eb-913b-860de6302b12.png)

![image](https://user-images.githubusercontent.com/13320319/106752771-1e206b00-662b-11eb-864e-daec58f5d125.png)

```
{result: "ok", data: {}}
data: {}
result: "ok"
```
I dunno what's going on here or how I can find the issue. If you might have a look in this. I guess this will impact other users with updated suervisor as well.

Please let me know if you need additional information.

**Comment by paularmstrong** [comment]
```
chunk.97b95a62afbc18471344.js:3350 Uncaught (in promise) TypeError: Cannot read property 'find' of null
    at HTMLElement.value (chunk.97b95a62afbc18471344.js:3350)
    at HTMLElement.performUpdate (entrypoint.cf81f6d9.js:35547)
    at HTMLElement._enqueueUpdate (entrypoint.cf81f6d9.js:35547)
```

```
Could not load content for webpack://home-assistant-frontend/chunk.97b95a62afbc18471344.js (HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME)
```

These are both errors stemming from Home Assistant's own code. Is 2021.02.1 in beta release? I don't see an announcement about it yet, but I'm guessing they changed something that we'll have to update for.

**Comment by thundergreen** [comment]
Nice to hear that someone took a look at it and yes I run currently 2021.02.5 .other add-ons work .this is the only add-on not running

**Comment by paularmstrong** [comment]
Is the entire addon not running or is just the web UI having issues? There are currently over 500 commits slated for this HA version and nothing is sticking out to me, but I could easily have missed something.

**Comment by HITChris** [comment]
[This](https://github.com/home-assistant/frontend/issues/8308) frontend issue seems related

**Comment by thundergreen** [comment]
@HITChris  absolutely! That's exactly what I face as well. No config template nor save function possible. Glad someone faces same issue

**Comment by blakeblackshear** [comment]
Have you tried clearing your browser cache? Or in incognito mode?

**Comment by thundergreen** [comment]
Yes both and it doesn't work at all

**Comment by thundergreen** [comment]
I just updated to latest Supervisor version with own Api for configuration

https://github.com/home-assistant/developers.home-assistant/pull/794/files

BUT i get still an error:

```
 * Starting nginx nginx
   ...done.
Error parsing config: 'mqtt'
```
With config:

```
detectors:
  coral:
    type: edgetpu
    device: pci
mqtt:
  host: 192.168.1.41
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: hass
  password: hass
ffmpeg:
  global_args:
  - "-hide_banner"
  - "-loglevel"
  - panic
  hwaccel_args:
  - "-hwaccel"
  - vaapi
  - "-hwaccel_device"
  - "/dev/dri/renderD128"
  - "-hwaccel_output_format"
  - yuv420p
  input_args:
  - "-avoid_negative_ts"
  - make_zero
  - "-fflags"
  - nobuffer
  - "-flags"
  - low_delay
  - "-strict"
  - experimental
  - "-fflags"
  - "+genpts+discardcorrupt"
  - "-rtsp_transport"
  - tcp
  - "-stimeout"
  - '5000000'
  - "-use_wallclock_as_timestamps"
  - '1'
cameras:
  front_door:
    ffmpeg:
      inputs:
      - path: rtsp://hass:hass@40.40.40.224:88/videoMain
        roles:
        - detect
        - rtmp
        - clips
        - record
    width: 1280
    height: 720
    fps: 15
    record:
      enabled: true
      retain_days: 1
    zones:
      parking:
        coordinates: '554,333,611,274,708,281,763,265,823,260,948,285,1021,341,1078,359,1102,387,1137,381,1154,417,1120,596,760,504,754,318'
      mailbox:
        coordinates: '416,454,434,401,387,346,336,395,337,446'
      main_door:
        coordinates: '1200,697,1159,699,1071,699,936,695,553,663,530,449,1280,420'
  porch:
    ffmpeg:
      inputs:
      - path: rtsp://hassio:hassio@40.40.40.92:554/stream1
        roles:
        - detect
        - rtmp
        - clips
        - record
    width: 1920
    height: 1080
    fps: 15
    record:
      enabled: true
      retain_days: 1
    zones:
      door_porch_dining_room:
        coordinates: '1243,1080,1292,85,961,162,929,1080'
  garage:
    ffmpeg:
      inputs:
      - path: rtsp://40.40.40.220:554/media/stream1
        roles:
        - detect
        - rtmp
        - clips
        - record
    width: 1280
    height: 720
    fps: 15
    record:
      enabled: true
      retain_days: 1
    zones:
      garage_door:
        coordinates: 0,158,0,504,383,493,397,213
      refrigiator:
        coordinates: '1186,259,1159,665,1038,646,1070,259'
      table:
        coordinates: '269,486,0,486,0,720,142,720,592,720,256,482,145,720,376,720,588,720'
      window_front_house:
        coordinates: '599,265,605,419,507,418,514,250'
  garden:
    ffmpeg:
      inputs:
      - path: rtsp://40.40.40.14:554/media/stream1
        roles:
        - detect
        - rtmp
        - clips
        - record
    width: 1280
    height: 720
    fps: 15
    record:
      enabled: true
      retain_days: 1
```

Config is saved but somehow not? Nothing in Chrome Console

this is in logs:

```
21-02-04 16:52:04 WARNING (MainThread) [supervisor.addons.options] Unknown options detectors
21-02-04 16:52:04 WARNING (MainThread) [supervisor.addons.options] Unknown options mqtt
21-02-04 16:52:04 WARNING (MainThread) [supervisor.addons.options] Unknown options ffmpeg
21-02-04 16:52:04 WARNING (MainThread) [supervisor.addons.options] Unknown options cameras
21-02-04 16:52:04 WARNING (MainThread) [supervisor.addons.options] Unknown options detectors
21-02-04 16:52:04 WARNING (MainThread) [supervisor.addons.options] Unknown options mqtt
21-02-04 16:52:04 WARNING (MainThread) [supervisor.addons.options] Unknown options ffmpeg
21-02-04 16:52:04 WARNING (MainThread) [supervisor.addons.options] Unknown options cameras
```

**Comment by Melkor82** [comment]
facing the same problem, now i can load the configuration but it stuk on the mqtt

**Comment by thundergreen** [comment]
is it related to the path? mine is 
```/usr/share/hassio/addons/data/ccab4aaf_frigate```
when i watch the api thing it's
```<ApiEndpoint path="/addons/<addon>/options/config" method="get">```

inside docker it's 

![image](https://user-images.githubusercontent.com/13320319/106927847-da089580-6712-11eb-91bb-7c779aa8d460.png)


Well might not be related but I try to find a way to get this addon working :(

**Comment by HITChris** [comment]
Supervisor-2021.02.4 appears to have resolved this in my case

**Comment by thundergreen** [comment]
Did it really solve your problem?

HIT Chris <notifications@github.com> schrieb am Fr., 5. Feb. 2021, 00:55:

**Comment by HITChris** [comment]
No. Same symptoms as you.

**Comment by paularmstrong** [comment]
Latest version is working fine for me. Looks like it was fixed in home-assistant/frontend#8322

**Comment by HITChris** [comment]
Odd. For me, that commit resolved the config editing issue (seemed like supervisor's UI for addon configs was defaulting to a schema-based input, rather than YAML, and so no schema in the addon's config.json was causing the UI's rendering to fail). But on my supervised install (and supervisor-2021.02.4), the json is still not being stored to /usr/share/hassio/addons/data/ccab4aaf_frigate/options.json upon add-on start. As a result I get the mqtt failure indicating missing mqtt config

**Comment by thundergreen** [comment]
> Odd. For me, that commit resolved the config editing issue (seemed like supervisor's UI for addon configs was defaulting to a schema-based input, rather than YAML, and so no schema in the addon's config.json was causing the UI's rendering to fail). But on my supervised install (and supervisor-2021.02.4), the json is still not being stored to /usr/share/hassio/addons/data/ccab4aaf_frigate/options.json upon add-on start. As a result I get the mqtt failure indicating missing mqtt config

That is exactly the issue! Well described . @paularmstrong would be interested how you fixed it? I am running supervised install and it does not yet offer new release. Hoping this will also fix our issue as well. Waitung next beta releaase then ...

**Comment by paularmstrong** [comment]
> @paularmstrong would be interested how you fixed it?

I didn't do anything. I'm running Home Assistant (the full OS) and I upgraded supervisor to the latest stable release and had no issues.

**Comment by thundergreen** [comment]
@paularmstrong we are talking about Supervisor version 2021.02.1 which is beta afaik.  And your home-assistant/frontend#8322 has been made yesterday. I fear you mix up something here :)

**Comment by paularmstrong** [comment]
Oh jeez. I hit update last night and know for sure that HA updated... turns out that it didn't actually install and I'm still on 2021.1.7.

**Comment by paularmstrong** [comment]
I guess the solution is to wait until the next bugfix release or roll your install back.

**Comment by thundergreen** [comment]
I will wait for a fix.. DON'T update :)

**Comment by HITChris** [comment]
Besides Texecom2Mqtt, I haven't seen other reports of similar issues with addon configs, so although the post-2021.1.7 change might get fixed at some point upstream, this might be something specific to the frigate addon. This issue should probably be closed/re-opened in blakeblackshear/frigate-hass-addons

**Comment by thundergreen** [comment]
@HITChris Do u want to create an issue?

**Comment by blakeblackshear** [comment]
It's fine here

**Comment by thundergreen** [comment]
@blakeblackshear did you get time to watch into this issue? Dpnt wanna bother just wanted to get some news as peopple using supervisor may run into the same issue and.. well.. I miss my cams :( :P

**Comment by blakeblackshear** [comment]
The linked issues for homeassistant indicate that this is not an issue with my addon. It is a bug in homeassistant.

**Comment by pdecat** [comment]
Sadly, Supervisor 2021.02.5 is out of beta, so it is now auto upgrading from 2021.01.x but the Frigate addon is still no longer compatible (same `Error parsing config: 'mqtt'` error as already reported above).

Downgrading to 2021.01.8 does not help as it will re-upgrade to 2021.02.5 right after startup:

```
root@hassio:~# docker exec -ti hassio_cli ha supervisor update --version 2021.01.8
Processing... Done.

Command completed successfully.
```

```
[11:35:50] INFO: Starting local supervisor watchdog...                                                                                                                                   
21-02-08 11:35:50 INFO (MainThread) [__main__] Initializing Supervisor setup                                                                                                             
...
21-02-08 11:35:59 INFO (MainThread) [__main__] Running Supervisor
21-02-08 11:35:59 INFO (MainThread) [supervisor.supervisor] Update Supervisor to version 2021.02.5
21-02-08 11:35:59 INFO (SyncWorker_5) [supervisor.docker.interface] Downloading docker image homeassistant/amd64-hassio-supervisor with tag 2021.02.5.
21-02-08 11:36:03 INFO (MainThread) [supervisor.supervisor] Fetching AppArmor profile https://version.home-assistant.io/apparmor.txt
21-02-08 11:36:03 INFO (MainThread) [supervisor.host.apparmor] Adding/updating AppArmor profile: hassio-supervisor
21-02-08 11:36:03 INFO (MainThread) [supervisor.host.services] Reloading local service hassio-apparmor.service
21-02-08 11:36:03 INFO (MainThread) [supervisor.api] Stopping API on 172.30.32.2
21-02-08 11:36:03 INFO (MainThread) [supervisor.misc.scheduler] Shutting down scheduled tasks
21-02-08 11:36:03 INFO (MainThread) [supervisor.core] Supervisor is down - 0
21-02-08 11:36:03 INFO (MainThread) [__main__] Closing Supervisor
```

**Comment by pdecat** [comment]
All frigate options are ignored here: https://github.com/home-assistant/supervisor/commit/6a0206c1e79deb2a91e5a2e14c804aa47b48bfcb#diff-76642712da34bc99ca9ab11ed525952ac94614d0b06c7343fe68dc68d3e4f644R76-R79

**Comment by blakeblackshear** [comment]
I think this will fix it when the change lands: https://github.com/home-assistant/frontend/pull/8322

**Comment by pdecat** [comment]
So did I, but this change has apparently already landed in supervisor 2021.02.5:

https://github.com/home-assistant/supervisor/commit/af4517fd1eb6e3df53b6110f8e78d23a9c584ec5

https://github.com/home-assistant/frontend/compare/e06642e892b0700ec414a93c1a976174d80d5126...4273b72d71883a1e723213b5adfd8615b0d8edce

**Comment by pdecat** [comment]
As a work-around, I've backed up a JSON formatted version of my configuration (used `faq` to convert from YAML to JSON) and installed a watch on the `option.json` file to replace it by the backup as soon as it is overwritten by supervisor:

```
root@hassio:~# while true ; do inotifywait /usr/share/hassio/addons/data/be8d440d_frigate-beta/options.json ; cp /usr/share/hassio/addons/data/be8d440d_frigate-beta/options.json{.bak,} 
; done
```

**Comment by blakeblackshear** [comment]
I'm really surprised that this isn't breaking lots of addons. It doesn't seem to be possible to disable schema validation and allow an open ended yaml configuration anymore. The schema validation builtin to the supervisor is not advanced enough for frigate. If that was intentional, I will have to move to reading the config file from homeassistant's config directory instead, and it will no longer be possible to use the addon configuration tab to edit your config.

**Comment by pdecat** [comment]
> I'm really surprised that this isn't breaking lots of addons

Indeed.

> If that was intentional, I will have to move to reading the config file from homeassistant's config directory instead, and it will no longer be possible to use the addon configuration tab to edit your config.

An alternative maybe to expose the config schema in the addon's config.json to allow supervisor to use it.

**Comment by blakeblackshear** [comment]
> An alternative may be to expose the config schema in the addon's config.json to allow supervisor to use it.

I don't think that will work because the developer docs state "Only nested arrays and dictionaries are supported with a deep of two size".

**Comment by rchamp26** [comment]
seeing same issue here. my deconz integration just updated to support the changes in the 2021.2.5 supervisor update. looks like supervisor doesn't like the config anymore here in frigate which is preventing the addon from fully starting up

**Comment by pdecat** [comment]
Looks like the fix is coming: https://github.com/home-assistant/supervisor/pull/2535

**Comment by pdecat** [comment]
> Looks like the fix is coming: [home-assistant/supervisor#2535](https://github.com/home-assistant/supervisor/pull/2535)

Or not...

Schema is becoming required in next version :confused: 

https://github.com/home-assistant/developers.home-assistant/pull/799/files#diff-3f08851d8fc8431ebfa303ef0751f9dab7937ade730d5930038f9c32924f50cbL150

**Comment by paularmstrong** [comment]
> > An alternative may be to expose the config schema in the addon's config.json to allow supervisor to use it.
> 
> I don't think that will work because the developer docs state "Only nested arrays and dictionaries are supported with a deep of two size".

If that's the case, does that mean either we need to change the config schema (big breaking change) or make it fully configurable via the UI so that it's optional to provide at startup?

**Comment by hawkeye217** [comment]
> As a work-around, I've backed up a JSON formatted version of my configuration (used `faq` to convert from YAML to JSON) and installed a watch on the `option.json` file to replace it by the backup as soon as it is overwritten by supervisor:
> 
> ```
> root@hassio:~# while true ; do inotifywait /usr/share/hassio/addons/data/be8d440d_frigate-beta/options.json ; cp /usr/share/hassio/addons/data/be8d440d_frigate-beta/options.json{.bak,} 
> ; done
> ```

Managed to do something similar to get the addon started again. Thanks for the tip.

**Comment by Bascht74** [comment]
@hawkeye217 As this is a problem for me, too, could you add some information how you installed the watch on the file?
Thx, Sebastian

**Comment by hawkeye217** [comment]
> @hawkeye217 As this is a problem for me, too, could you add some information how you installed the watch on the file?
> Thx, Sebastian

What I did was not as elegant as @pdecat, and it's a hack... 

I converted my yaml to json via ```yq eval -j config.yml```, then logged into the supervisor container via ```docker exec -it hassio_supervisor /bin/bash```, then cut/paste my json into a new file called options2.json.  Frigate's ```options.json``` was  accessible under ```/data/addons/data/ccab4aaf_frigate```, so I ran this:

```# while true; do cp options2.json /data/addons/data/ccab4aaf_frigate/options.json; done```

It took a few attempts to start the addon, but once it started, I just hit ctrl-c to stop the copy madness and all was good.

Definitely not a permanent solution, but it at least got the addon started again.

**Comment by bratanon** [comment]
> I will have to move to reading the config file from homeassistant's config directory instead,

That I would love. Dont understand all this "in app configuration" that can not be version handled.

**Comment by blakeblackshear** [comment]
Just pushed a new version of the addon. Frigate's config can no longer be managed in the `Configuration` tab of the addon (at least for now). The addon expects a `frigate.yml` file to exist in the root of your homeassistant config directory. You can edit it using whatever editor you use for homeassistant config.

> That I would love. Dont understand all this "in app configuration" that can not be version handled.

If you are using HassOS the snapshots take backups of your addon config too, but this is exactly why frigate does not have the ability to modify it's own config. Even when it does, it will always just be a UI for modifying the config file with a clear option for those who want to save it out into source control since this is how I do it. There will never be a `.storage` folder for frigate.

**Comment by madmic1314** [comment]
Is it possible for this fix be pushed to those using the beta?

**Comment by geyles** [comment]
I'm running latest frigate addon in latest HA and I'm stilling getting Error parsing config: 'mqtt'
I've tried placing a frigate.yml (and frigate.yaml in case) and still had no look getting it working.

**Comment by pdecat** [comment]
> Frigate's config can no longer be managed in the `Configuration` tab of the addon (at least for now). The addon expects a `frigate.yml` file to exist in the root of your homeassistant config directory. You can edit it using whatever editor you use for homeassistant config.

Good move:

- https://github.com/home-assistant/developers.home-assistant/pull/800
- https://github.com/home-assistant/frontend/pull/8361

**Comment by lukaszolek** [comment]
@blakeblackshear thank you for the update. Config file works well.
I have a question - is there an easy way to reload the configuration after it's changed? Do I need to restart the whole frigate to do it?

**Comment by blakeblackshear** [comment]
A restart is required.

**Comment by blakeblackshear** [comment]
> Is it possible for this fix be pushed to those using the beta?

The beta is older than the stable version. Why would you be using it?

**Comment by pdecat** [comment]
https://github.com/home-assistant/frontend/pull/8361 was merged, beware to backup existing addon configuration before upgrading to next supervior release or you won't be able to retrieve it.

**Comment by madmic1314** [comment]
> > Is it possible for this fix be pushed to those using the beta?
> 
> The beta is older than the stable version. Why would you be using it?

I wasn't aware of this. I was running the Beta as there were was options I liked ahead of stable. I'll upgrade!

**Comment by floris-b** [comment]
I now have to turn off protection mode for frigate to find the USB TPU

**Comment by blakeblackshear** [comment]
> I now have to turn off protection mode for frigate to find the USB TPU

That has always been true for me. Not sure why yours would have worked with protection mode on before.

**Comment by mwy6283** [comment]
Hi I been reading this thread  i believe that i have this issue  where the Frigate add on will not  run. when I look at the  addon log and supervisor log .  I have been trying to install this addon for 10 days now. any help would be appreciated.
addon log
* Starting nginx nginx
   ...done.
Error parsing config: expected a list for dictionary value @ data['cameras']['back']['ffmpeg']['inputs'][0]['roles']

supervisor log:
21-04-06 12:02:14 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
21-04-06 12:02:15 WARNING (MainThread) [supervisor.addons.validate] Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of Frigate NVR
21-04-06 12:02:15 WARNING (MainThread) [supervisor.addons.validate] Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of Frigate NVR Beta (outdated)
21-04-06 12:02:15 WARNING (MainThread) [supervisor.addons.validate] Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of Frigate NVR
21-04-06 12:02:15 WARNING (MainThread) [supervisor.addons.validate] Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of Frigate NVR Beta (outdated)
21-04-06 12:02:15 INFO (MainThread) [supervisor.store] Loading add-ons from store: 68 all - 0 new - 0 remove
21-04-06 12:02:15 INFO (MainThread) [supervisor.store] Loading add-ons from store: 68 all - 0 new - 0 remove
21-04-06 12:22:15 INFO (MainThread) [supervisor.host.info] Updating local host information
21-04-06 12:22:15 INFO (MainThread) [supervisor.host.services] Updating service information
21-04-06 12:22:15 INFO (MainThread) [supervisor.host.network] Updating local network information
21-04-06 12:22:15 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
21-04-06 12:22:15 INFO (MainThread) [supervisor.host] Host information reload completed

**Comment by heikkis** [comment]
@mwy6283 The error says that roles has wrong type of value in the pointed path. If you share your config then someone can help to solve your problem.

**Comment by HITChris** [comment]
From the parsing error in your log, your yaml config is improperly formatted. Either try starting from scratch, with a copy of the example config from the documentation. Or else open an Issue, and paste your config there.
