### ISSUE TITLE
[Config Support]: Autodelete of old recordings does seem to work

### ISSUE THREAD

**Issue by Diondk** [blakeblackshear/frigate#7299]
### Describe the problem you are having

I have a retain of 45 days on all camera's for some reason i still have data from december on my disk. 
Totally frigate is consuming 4~5 TB of data for the last 6 months while the retaining days is set to 45 

Is there a way to manually start the cleanup? also the database on the disk is 5 GB. 

### Version

0.12.1-367D724

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb:0
mqtt:
  host: x.x.x.x
  port: 1883
  user: xxxx
  password: xxx
  topic_prefix: frigate
  client_id: frigate
# Optional: Database configuration
database:
  # The path to store the SQLite DB (default: shown below)
  path: /media/frigate/frigate.db
cameras:
  oprit:
    ffmpeg:
      inputs:
        - path: rtsp://xxxx:xxx@x.x.x.x:88/videoMain
          roles:
            - record
            - detect
            - rtmp
    zones:    # Optional: zones for this camera
      driveway:
        coordinates: 2024,1440,2232,399,1469,217,0,0,0,1263,0,1440
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.7
    objects:
      track:
        - person
        - dog
        - car
      filters:
        person:
          min_score: 0.8
          threshold: 0.8
        dog:
          max_area: 10000
          min_score: 0.7
          threshold: 0.7
        car:
          min_score: 0.75
          threshold: 0.75
          min_area: 150000
          mask:
            - 596,686,1414,243,2226,463,1973,1440,0,1440
    record:
      enabled: true
      expire_interval: 60
      retain:
        days: 45
        mode: all
    detect:
      max_disappeared: 150
      width: 2560
      height: 1440
      fps: 25
    motion:
      mask:
        - 220,1440,101,1243,645,731,1496,187,2235,388,1981,1440
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 270
  achtertuin:
    ffmpeg:
      inputs:
        - path: rtsp://admin:x.x.x.x@x.x.x.x.x./cam/realmonitor?channel=1&subtype=00&authbasic=YWRtaW46TEUyMUVCNDlC
          roles:
            - record
            - detect
      input_args:
        - -c:v
        - h264_cuvid
    record:
      enabled: True
      retain:
        days: 45      
    #motion: # Optional: camera level motion config
    #  mask: 639,572,303,595,183,1080,0,1080,0,0,680,0
    best_image_timeout: 60     # to be replaced by a newer image. (default: shown below)
    # Optional: Configuration for the jpg snapshots published via MQTT
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: True
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: True
      # Optional: height to resize the snapshot to (default: shown below)
      height: 270
    detect:     # Optional: Camera level detect settings
      enabled: True # This value can be set via MQTT and will be updated in startup based on retained value
      max_disappeared: 20  # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: double the frame rate)
      width: 2560 # Required: width of the frame for the input with the detect role
      height: 1440 # Required: height of the frame for the input with the detect role
      fps: 5 # Optional: desired fps for your camera for the input with the detect role
  woonkamer:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxx@x.x.x.x:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record
            - detect
      input_args:
        - -c:v
        - h264_cuvid
    detect:     # Optional: Camera level detect settings
      #enabled: True # This value can be set via MQTT and will be updated in startup based on retained value
      max_disappeared: 20  # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: double the frame rate)
      width: 1920 # Required: width of the frame for the input with the detect role
      height: 1080 # Required: height of the frame for the input with the detect role
      fps: 5 # Optional: desired fps for your camera for the input with the detect role
    record:
      enabled: true
      retain:
        days: 45      
    # Optional: Configuration for the jpg snapshots published via MQTT
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: True
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: True
      # Optional: height to resize the snapshot to (default: shown below)
      height: 270
  Chloe:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxx@x.x.x.x:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
      input_args:
        - -c:v
        - h264_cuvid
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 270
    record:
      enabled: True
      retain: 
        days: 45       
record:
  enabled: true
  retain:
    days: 45
  events:
    # Optional: Maximum length of time to retain video during long events. (default: shown below)
    # NOTE: If an object is being tracked for longer than this amount of time, the retained recordings
    #       will be the last x seconds of the event unless retain->days under record is > 0.
    #max_seconds: 300
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 5
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
      - person
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 45

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
  # Optional: filters to reduce false positives for specific object types
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      max_area: 100000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.7
      
ffmpeg:
   hwaccel_args: -c:v h264_cuvid
  # output_args:   
    # # Optional: output args for detect streams (default: shown below)
    # detect: -f rawvideo -pix_fmt yuv420p -filter:v fps=fps=5
    # # Optional: output args for record streams (default: shown below)
    # record: -f segment -segment_time 300 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
    # # Optional: output args for clips streams (default: shown below)
    # #clips: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    # # Optional: output args for rtmp streams (default: shown below)
    # #rtmp: -c copy -f flv
logger:
  # Optional: default log level (default: shown below)
  default: info
  # Optional: module by module log level configuration
  logs:
    frigate.mqtt: debug
```

### Relevant log output

```shell
2023-07-27 10:33:38.053631732  [INFO] Starting Frigate...
2023-07-27 10:33:39.503104556  [2023-07-27 10:33:39] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-07-27 10:33:39.537566246  [2023-07-27 10:33:39] peewee_migrate                 INFO    : Starting migrations
2023-07-27 10:33:39.734155043  [2023-07-27 10:33:39] peewee_migrate                 INFO    : There is nothing to migrate
2023-07-27 10:33:39.750859814  [2023-07-27 10:33:39] detector.coral                 INFO    : Starting detection process: 583
2023-07-27 10:33:42.368350717  [2023-07-27 10:33:39] frigate.app                    INFO    : Output process started: 586
2023-07-27 10:33:42.370332606  [2023-07-27 10:33:39] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb:0
2023-07-27 10:33:42.370392100  [2023-07-27 10:33:39] frigate.app                    INFO    : Camera processor started for oprit: 593
2023-07-27 10:33:42.370461366  [2023-07-27 10:33:42] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-07-27 10:33:42.370539893  [2023-07-27 10:33:39] frigate.app                    INFO    : Camera processor started for achtertuin: 594
2023-07-27 10:33:42.370612865  [2023-07-27 10:33:39] frigate.app                    INFO    : Camera processor started for woonkamer: 596
2023-07-27 10:33:42.370673231  [2023-07-27 10:33:39] frigate.app                    INFO    : Camera processor started for Chloe: 597
2023-07-27 10:33:42.370701565  [2023-07-27 10:33:39] frigate.app                    INFO    : Capture process started for oprit: 599
2023-07-27 10:33:42.370753716  [2023-07-27 10:33:39] frigate.app                    INFO    : Capture process started for achtertuin: 602
2023-07-27 10:33:42.370826607  [2023-07-27 10:33:39] frigate.app                    INFO    : Capture process started for woonkamer: 608
2023-07-27 10:33:42.370898971  [2023-07-27 10:33:39] frigate.app                    INFO    : Capture process started for Chloe: 612
```

### Frigate stats

```json
{"Chloe":{"camera_fps":5.1,"capture_pid":612,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":620,"pid":597,"process_fps":5.1,"skipped_fps":0.0},"achtertuin":{"camera_fps":5.0,"capture_pid":602,"detection_enabled":1,"detection_fps":11.5,"ffmpeg_pid":606,"pid":594,"process_fps":5.0,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.3"},"1":{"cpu":"0.0","mem":"0.0"},"103":{"cpu":"0.0","mem":"0.0"},"104":{"cpu":"30.3","mem":"2.7"},"1141":{"cpu":"0.0","mem":"0.0"},"1176":{"cpu":"0.0","mem":"0.0"},"118":{"cpu":"0.0","mem":"0.0"},"1181":{"cpu":"0.0","mem":"0.0"},"140":{"cpu":"0.0","mem":"0.0"},"141":{"cpu":"0.0","mem":"0.0"},"143":{"cpu":"0.0","mem":"0.0"},"154":{"cpu":"0.0","mem":"0.0"},"179":{"cpu":"0.0","mem":"0.0"},"21":{"cpu":"0.0","mem":"0.0"},"210":{"cpu":"0.0","mem":"0.0"},"22":{"cpu":"0.0","mem":"0.0"},"242":{"cpu":"0.0","mem":"0.0"},"273":{"cpu":"0.0","mem":"0.0"},"30":{"cpu":"0.0","mem":"0.0"},"302":{"cpu":"0.0","mem":"0.0"},"31":{"cpu":"0.0","mem":"0.0"},"32":{"cpu":"0.0","mem":"0.0"},"33":{"cpu":"0.0","mem":"0.0"},"335":{"cpu":"0.0","mem":"0.0"},"34":{"cpu":"0.0","mem":"0.0"},"35":{"cpu":"0.0","mem":"0.0"},"36":{"cpu":"0.0","mem":"0.0"},"37":{"cpu":"0.0","mem":"0.0"},"375":{"cpu":"0.0","mem":"0.0"},"38":{"cpu":"0.0","mem":"0.0"},"412":{"cpu":"0.0","mem":"0.0"},"47":{"cpu":"0.0","mem":"0.0"},"48":{"cpu":"0.0","mem":"0.0"},"576":{"cpu":"0.0","mem":"0.4"},"582":{"cpu":"0.3","mem":"0.0"},"583":{"cpu":"12.7","mem":"0.4"},"586":{"cpu":"3.0","mem":"0.4"},"593":{"cpu":"38.7","mem":"0.4"},"594":{"cpu":"24.7","mem":"0.4"},"595":{"cpu":"0.0","mem":"0.0"},"596":{"cpu":"0.3","mem":"0.4"},"597":{"cpu":"5.0","mem":"0.4"},"598":{"cpu":"0.0","mem":"0.0"},"599":{"cpu":"14.7","mem":"0.4"},"602":{"cpu":"3.0","mem":"0.4"},"603":{"cpu":"15.0","mem":"0.5"},"606":{"cpu":"18.7","mem":"0.4"},"607":{"cpu":"0.0","mem":"0.0"},"608":{"cpu":"1.3","mem":"0.4"},"612":{"cpu":"1.0","mem":"0.4"},"613":{"cpu":"12.3","mem":"0.4"},"618":{"cpu":"0.0","mem":"0.0"},"620":{"cpu":"10.0","mem":"0.4"},"622":{"cpu":"0.0","mem":"0.0"},"86":{"cpu":"0.0","mem":"0.0"},"87":{"cpu":"0.0","mem":"0.0"},"88":{"cpu":"0.0","mem":"0.0"},"95":{"cpu":"0.0","mem":"0.0"},"MiB":{"cpu":"36275.8","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":39.9,"detectors":{"coral":{"detection_start":0.0,"inference_speed":7.72,"pid":583}},"gpu_usages":{"NVIDIA GeForce GTX 1050 Ti":{"gpu":"5 %","mem":"17.8 %"}},"oprit":{"camera_fps":25.0,"capture_pid":599,"detection_enabled":1,"detection_fps":26.8,"ffmpeg_pid":603,"pid":593,"process_fps":25.0,"skipped_fps":0.0},"service":{"last_updated":1690447084,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":245.4,"mount_type":"tmpfs","total":268.4,"used":23.1},"/media/frigate/clips":{"free":5364376.6,"mount_type":"fuse.shfs","total":40994834.2,"used":35630457.7},"/media/frigate/recordings":{"free":5364376.6,"mount_type":"fuse.shfs","total":40994834.2,"used":35630457.7},"/tmp/cache":{"free":82.2,"mount_type":"tmpfs","total":100.0,"used":17.9}},"temperatures":{},"uptime":265,"version":"0.12.1-367d724"},"woonkamer":{"camera_fps":5.1,"capture_pid":608,"detection_enabled":1,"detection_fps":1.6,"ffmpeg_pid":613,"pid":596,"process_fps":5.1,"skipped_fps":0.0}}
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

USB

**Comment by blakeblackshear** [comment]
Do you see these recordings in Frigate's UI? If not, then you probably deleted your database at some point and Frigate has no idea those files are there. You can delete them if so. 

The job to expire recordings runs every hour, but you can set it to something else in your config with the `expire_interval` value.

**Comment by Diondk** [comment]
Yes i still see the recordings in frigate, i can click on a date in december and on an hour and then the recording starts playing. 

I will try to change the expire_interval and see if it starts removing anything

**Comment by blakeblackshear** [comment]
Interesting. I think we have already addressed this for the next version.

Try increasing your retain value so it will try and expire fewer recordings at once. Looks like it's trying to remove too many at once. You can work it back down to 45 after a few expiration runs.

**Comment by Diondk** [comment]
Ok will try it and let you know if i succeeded.

**Comment by blakeblackshear** [comment]
Based on where this error is happening in the code, it appears to be related to a deleted or renamed camera. Make sure you set the retain days value globally.

**Comment by Diondk** [comment]
Ok i removed the settings for the retain days value per camera and only added it under record so that i have it globally, i have it set to keep 210 days but still get the same error.

**Comment by NickM-27** [comment]
So I have a PR up to fix this issue but it is part of the 0.13 release which won't be fully released for some time (but the beta is coming soonTM)

There are a few different ways you could fix this for your setup in the interim:
- Stop frigate and use sqlite3 to manually delete the entries for the old camera names that are not used anymore
- Delete all recordings and delete the entire DB file

**Comment by NickM-27** [comment]
Just fyi you will need to remove those recordings manually, without the db entry frigate does not know they exist

**Comment by Diondk** [comment]
So at the end i had a total of 1 year of data keeping 14 TB of space.. and i was wondering why my unraid was getting so full so fast.. 

overnight it has been cleared out, thanks for the help!

**Comment by NickM-27** [comment]
Just wanted to note the exception seen that prevented this from happening automatically has been fixed for 0.13

**Comment by hughc-hub** [comment]
I've just updated to v0.14.. I'm pretty amazed about the new features.. everything is working as expected!!

But my old recordings, are on my network disk , and now they are not reachable because they were created with v0.13 , aren't they? is there a way to safety delete them to save space?

thanks
