### ISSUE TITLE
"No Frames have been received" after enabling tensorrt detector

### ISSUE THREAD

**Issue by LukaszSoba** [blakeblackshear/frigate#8406]
### Describe the problem you are having

Hello,
I running Frigate since few days and it works great, 
I have installed  NVIDIA-SMI 535.54.03 ( nVidia GTX 750 Ti card ) and hardware acceleration works fine. 
I've tried to enable tensorrt on many ways but no luck.
In nvidia-smi panel i see process running and consuming some vga card ram, but when frigate starts i only see black 
thumbnails without images.
Tried evertyhing i guess every option passing GPU to container and i guess it's fine, propably some small mistake i cant solve myself.

In the beginnig also generated tensorrt models manually but i think system can also genete them automatically ? 

In the beginning I installed frigate on debian on bare metal, and theres no difference between with debian on proxmox.

The only difference is on proxmox there must be GPU passthrough requierements done, and nvidia-smi works the same.

Please help.
 

### Version

0.13.0-cd64399

### Frigate config file

```yaml
detectors:
  tensorrt:
    type: tensorrt

model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320

cameras:

# KAMERA PIWNICA  
  kamera_piwnica:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:admin@10.19.85.245:80/0
          roles:
            - detect
            - record
    record: 
      enabled: true
    snapshots: 
      enabled: true
    detect: 
      enabled: true
    objects: 
      track:
        - person
```

### docker-compose file or Docker CLI command

```yaml
# Frigate 0.13.0-beta3-tensorrt
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.13.0-beta3-tensorrt
    runtime: nvidia
    shm_size: "512mb"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/lukasz/frigate/config/:/config/
      - /mnt/frigate_dysk1:/media/frigate
      - type: tmpfs 
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
```

### Relevant log output

```shell
2023-10-31 22:07:10.994633573  [INFO] Preparing Frigate...
2023-10-31 22:07:11.015893568  [INFO] Starting Frigate...
2023-10-31 22:07:12.491748451  [2023-10-31 22:07:12] frigate.app                    INFO    : Starting Frigate (0.13.0-cd64399)
2023-10-31 22:07:22.999443476  [2023-10-31 22:07:22] peewee_migrate.logs            INFO    : Starting migrations
2023-10-31 22:07:23.002940645  [2023-10-31 22:07:23] peewee_migrate.logs            INFO    : There is nothing to migrate
2023-10-31 22:07:23.007737076  [2023-10-31 22:07:23] frigate.app                    INFO    : Recording process started: 256
2023-10-31 22:07:23.010282664  [2023-10-31 22:07:23] frigate.app                    INFO    : go2rtc process pid: 99
2023-10-31 22:07:23.034092754  [2023-10-31 22:07:23] frigate.app                    INFO    : Output process started: 266
2023-10-31 22:07:23.057997017  [2023-10-31 22:07:23] frigate.app                    INFO    : Camera processor started for kamera_piwnica: 273
2023-10-31 22:07:23.064831332  [2023-10-31 22:07:23] frigate.app                    INFO    : Camera processor started for kamera_brama: 274
2023-10-31 22:07:23.067043699  [2023-10-31 22:07:23] frigate.app                    INFO    : Camera processor started for kamera_drzwi: 276
2023-10-31 22:07:23.076934390  [2023-10-31 22:07:23] frigate.app                    INFO    : Camera processor started for kamera_ogrod: 277
2023-10-31 22:07:23.090779273  [2023-10-31 22:07:23] frigate.app                    INFO    : Capture process started for kamera_piwnica: 278
2023-10-31 22:07:23.109241379  [2023-10-31 22:07:23] frigate.app                    INFO    : Capture process started for kamera_brama: 280
2023-10-31 22:07:23.130814240  [2023-10-31 22:07:23] frigate.app                    INFO    : Capture process started for kamera_drzwi: 290
2023-10-31 22:07:23.152743826  [2023-10-31 22:07:23] frigate.app                    INFO    : Capture process started for kamera_ogrod: 294
2023-10-31 22:07:23.307650797  [2023-10-31 22:07:23] detector.tensorrt              INFO    : Starting detection process: 265
2023-10-31 22:07:23.386753263  [2023-10-31 22:07:23] frigate.detectors.plugins.tensorrt INFO    : Loaded engine size: 174 MiB
2023-10-31 22:07:23.516332300  [2023-10-31 22:07:23] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +6, GPU +8, now: CPU 300, GPU 215 (MiB)
2023-10-31 22:07:23.520449289  [2023-10-31 22:07:23] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuDNN: CPU +2, GPU +10, now: CPU 302, GPU 225 (MiB)
2023-10-31 22:07:23.528964982  [2023-10-31 22:07:23] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +174, now: CPU 0, GPU 174 (MiB)
2023-10-31 22:07:23.528969160  [2023-10-31 22:07:23] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 128, GPU 218 (MiB)
2023-10-31 22:07:23.528970934  [2023-10-31 22:07:23] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 128, GPU 226 (MiB)
2023-10-31 22:07:23.529269455  [2023-10-31 22:07:23] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +29, now: CPU 0, GPU 203 (MiB)
2023-10-31 22:07:31.480630956  Process camera_processor:kamera_brama:
2023-10-31 22:07:31.481467533  Traceback (most recent call last):
2023-10-31 22:07:31.481470072    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-10-31 22:07:31.481471118      self.run()
2023-10-31 22:07:31.481472209    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-10-31 22:07:31.481473183      self._target(*self._args, **self._kwargs)
2023-10-31 22:07:31.481474116    File "/opt/frigate/frigate/video.py", line 432, in track_camera
2023-10-31 22:07:31.481475007      process_frames(
2023-10-31 22:07:31.481475977    File "/opt/frigate/frigate/video.py", line 685, in process_frames
2023-10-31 22:07:31.481478764      detect(
2023-10-31 22:07:31.481479820    File "/opt/frigate/frigate/video.py", line 470, in detect
2023-10-31 22:07:31.481480852      region_detections = object_detector.detect(tensor_input)
2023-10-31 22:07:31.481481860    File "/opt/frigate/frigate/object_detection.py", line 225, in detect
2023-10-31 22:07:31.481500892      (self.labels[int(d[0])], float(d[1]), (d[2], d[3], d[4], d[5]))
2023-10-31 22:07:31.481501900  KeyError: -14
2023-10-31 22:07:31.543042163  Process camera_processor:kamera_piwnica:
2023-10-31 22:07:31.543760711  Traceback (most recent call last):
2023-10-31 22:07:31.543841957    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-10-31 22:07:31.543843459      self.run()
2023-10-31 22:07:31.543844615    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-10-31 22:07:31.543845668      self._target(*self._args, **self._kwargs)
2023-10-31 22:07:31.543846675    File "/opt/frigate/frigate/video.py", line 432, in track_camera
2023-10-31 22:07:31.543847533      process_frames(
2023-10-31 22:07:31.543848499    File "/opt/frigate/frigate/video.py", line 685, in process_frames
2023-10-31 22:07:31.543849334      detect(
2023-10-31 22:07:31.543850303    File "/opt/frigate/frigate/video.py", line 470, in detect
2023-10-31 22:07:31.543851290      region_detections = object_detector.detect(tensor_input)
2023-10-31 22:07:31.543852245    File "/opt/frigate/frigate/object_detection.py", line 225, in detect
2023-10-31 22:07:31.543853249      (self.labels[int(d[0])], float(d[1]), (d[2], d[3], d[4], d[5]))
2023-10-31 22:07:31.543854038  KeyError: -21
2023-10-31 22:07:31.921221479  [2023-10-31 22:07:31] frigate.video                  ERROR   : kamera_piwnica: Unable to read frames from ffmpeg process.
2023-10-31 22:07:31.921478542  [2023-10-31 22:07:31] frigate.video                  ERROR   : kamera_piwnica: ffmpeg process is not running. exiting capture thread...
2023-10-31 22:07:32.619983753  Process camera_processor:kamera_ogrod:
2023-10-31 22:07:32.619987436  Traceback (most recent call last):
2023-10-31 22:07:32.619988673    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-10-31 22:07:32.619989627      self.run()
2023-10-31 22:07:32.619990742    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-10-31 22:07:32.619991702      self._target(*self._args, **self._kwargs)
2023-10-31 22:07:32.619992692    File "/opt/frigate/frigate/video.py", line 432, in track_camera
2023-10-31 22:07:32.619993548      process_frames(
2023-10-31 22:07:32.619994567    File "/opt/frigate/frigate/video.py", line 685, in process_frames
2023-10-31 22:07:32.619995378      detect(
2023-10-31 22:07:32.619996363    File "/opt/frigate/frigate/video.py", line 470, in detect
2023-10-31 22:07:32.619997342      region_detections = object_detector.detect(tensor_input)
2023-10-31 22:07:32.619998302    File "/opt/frigate/frigate/object_detection.py", line 225, in detect
2023-10-31 22:07:32.619999277      (self.labels[int(d[0])], float(d[1]), (d[2], d[3], d[4], d[5]))
2023-10-31 22:07:32.620000061  KeyError: -13
2023-10-31 22:07:32.732192125  Process camera_processor:kamera_drzwi:
2023-10-31 22:07:32.732602311  Traceback (most recent call last):
2023-10-31 22:07:32.732663479    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-10-31 22:07:32.732664991      self.run()
2023-10-31 22:07:32.732666127    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-10-31 22:07:32.732667160      self._target(*self._args, **self._kwargs)
2023-10-31 22:07:32.732668193    File "/opt/frigate/frigate/video.py", line 432, in track_camera
2023-10-31 22:07:32.732669082      process_frames(
2023-10-31 22:07:32.732670132    File "/opt/frigate/frigate/video.py", line 685, in process_frames
2023-10-31 22:07:32.732670985      detect(
2023-10-31 22:07:32.732671949    File "/opt/frigate/frigate/video.py", line 470, in detect
2023-10-31 22:07:32.732672911      region_detections = object_detector.detect(tensor_input)
2023-10-31 22:07:32.732673888    File "/opt/frigate/frigate/object_detection.py", line 225, in detect
2023-10-31 22:07:32.732674884      (self.labels[int(d[0])], float(d[1]), (d[2], d[3], d[4], d[5]))
2023-10-31 22:07:32.732675664  KeyError: -14
```

### Operating system

Linux Debian

### Install method

Proxmox

### Coral version

No

**Comment by NickM-27** [comment]
What GPU is this? This may be a duplicate of https://github.com/blakeblackshear/frigate/issues/8329

**Comment by LukaszSoba** [comment]
It's nvidia GTX 750 Ti. 
Just now installed latest nvidia drivers NVIDIA-SMI 545.29.02 
So it seems it's seems my card is legacy hardware ? maybe i should use some older yolo library ?

**Comment by NickM-27** [comment]
The 750Ti supports compute capability 5.0 which means it should be working as expected. You might try adding `USE_FP16=False` to the env variables in the frigate docker compose to see if that changes anything

**Comment by LukaszSoba** [comment]
I've changed model to 
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video      
      - YOLO_MODELS=yolov4-608
      - USE_FP16=False
      
No difference, I still see in nvidia-smi how process frigate.detector.tensorrt i cosmuming memory, but no stream on cameras.

In some users configs of frigate i se something like this 

model:
  path: /yolo4/yolov4-tiny-416.trt
  labelmap_path: /labelmap.txt     <----- ???

**Comment by NickM-27** [comment]
Now that the driver has changed, please delete the /config/model_cache directory so the model can regenerate

**Comment by LukaszSoba** [comment]
Yes, that's the very basic information from the manual.

**Comment by NickM-27** [comment]
If that doesn't help then no idea, index error of - wouldn't be a valid index for the labelmap

**Comment by NickM-27** [comment]
Going to close this as a duplicate of https://github.com/blakeblackshear/frigate/issues/8329 so we can keep all info tracked in the same place
