### ISSUE TITLE
[Support]: Unable to open database file

### ISSUE THREAD

**Issue by IncognitoTGT** [blakeblackshear/frigate#8694]
### Describe the problem you are having

When I try to run Frigate on a Raspberry Pi 5, I get this error and Frigate restarts:

`Error importing detector runtime: /usr/local/lib/python3.9/dist-packages/openvino/pyopenvino.cpython-39-aarch64-linux-gnu.so: ELF load command alignment not page-aligned`

### Version

Latest as of 11/20, 6:49PM EST

### Frigate config file

```yaml
database:
  path: /db/frigate.db
mqtt:
  enabled: False

cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://10.53.19.30:8554/driveway-cam # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: False # <---- disable detection until you have a working camera feed
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
```

### Relevant log output

```shell
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
2023-11-20 18:44:24.352272233  [INFO] Preparing go2rtc config...
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
2023-11-20 18:44:24.365969204  [INFO] Starting Frigate...
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
2023-11-20 18:44:24.374014349  [INFO] Starting NGINX...
s6-rc: info: service legacy-services successfully started
2023-11-20 18:44:24.662903960  [INFO] Starting go2rtc...
2023-11-20 18:44:24.790214000  18:44:24.790 INF go2rtc version 1.2.0 linux/arm64
2023-11-20 18:44:24.790693779  18:44:24.790 INF [api] listen addr=:1984
2023-11-20 18:44:24.791092558  18:44:24.791 INF [rtsp] listen addr=:8554
2023-11-20 18:44:24.791440466  18:44:24.791 INF [srtp] listen addr=:8443
2023-11-20 18:44:24.791725651  18:44:24.791 INF [webrtc] listen addr=:8555
2023-11-20 18:44:25.664759254  Error importing detector runtime: /usr/local/lib/python3.9/dist-packages/openvino/pyopenvino.cpython-39-aarch64-linux-gnu.so: ELF load command alignment not page-aligned
2023-11-20 18:44:25.905873031  [2023-11-20 18:44:25] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-11-20 18:44:25.913965732  unable to open database file
2023-11-20 18:44:25.914269992  [2023-11-20 18:44:25] peewee_migrate                 INFO    : Starting migrations
2023-11-20 18:44:27.197703770  [INFO] Service Frigate exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2023-11-20 18:44:27.223182986  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2023-11-20 18:44:27.274561195  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
2023-11-20 18:44:27.279853687  exit OK
s6-rc: info: service nginx-log successfully stopped
2023-11-20 18:44:27.284724881  [INFO] The go2rtc service exited with code 0 (by signal 0)
s6-rc: info: service frigate-log successfully stopped
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service frigate-log successfully started
s6-rc: info: service nginx-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
2023-11-20 18:44:32.694877718  [INFO] Preparing go2rtc config...
2023-11-20 18:44:32.698100039  [INFO] Starting Frigate...
s6-rc: info: service go2rtc-healthcheck successfully started
2023-11-20 18:44:32.701966824  [INFO] Starting NGINX...
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
2023-11-20 18:44:33.062459626  [INFO] Starting go2rtc...
2023-11-20 18:44:33.146116953  18:44:33.146 INF go2rtc version 1.2.0 linux/arm64
2023-11-20 18:44:33.146489768  18:44:33.146 INF [api] listen addr=:1984
2023-11-20 18:44:33.146796065  18:44:33.146 INF [rtsp] listen addr=:8554
2023-11-20 18:44:33.147046269  18:44:33.147 INF [srtp] listen addr=:8443
2023-11-20 18:44:33.147281511  18:44:33.147 INF [webrtc] listen addr=:8555
```

### FFprobe output from your camera

```shell
ffprobe version 5.1.3-1+rpt4 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr --extra-version=1+rpt4 --toolchain=hardened --incdir=/usr/include/aarch64-linux-gnu --enable-gpl --disable-stripping --disable-mmal --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sand --enable-sdl2 --disable-sndio --enable-libjxl --enable-neon --enable-v4l2-request --enable-libudev --enable-epoxy --libdir=/usr/lib/aarch64-linux-gnu --arch=arm64 --enable-pocketsphinx --enable-librsvg --enable-libdc1394 --enable-libdrm --enable-vout-drm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[rtsp @ 0x5555a158bad0] method SETUP failed: 461 Unsupported Transport
Input #0, rtsp, from 'rtsp://10.53.19.30:8554/driveway-cam':
  Metadata:
    title           : No Name
  Duration: N/A, start: 0.446500, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x1080, 20 fps, 20 tbr, 90k tbn
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Mixed

### Camera make and model

Wyze - Using mrlt8/docker-wyze-bridge for RTSP

**Comment by IncognitoTGT** [comment]
Update: It started, but I'm still confused about it crashing

**Comment by NickM-27** [comment]
That's expected on some OS and not a problem, the reason frigate is having an issue is `unable to open database file`

**Comment by NickM-27** [comment]
what is the docker compose?

**Comment by IncognitoTGT** [comment]
```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "164mb" # update for your cameras based on calculation above
#    devices:
#      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/config.yml:/config/config.yml
      - ./media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "Fr!g!d1"
      ```

**Comment by NickM-27** [comment]
what type of mount is ./media

**Comment by IncognitoTGT** [comment]
Folder

**Comment by NickM-27** [comment]
right, but is it on an HDD, SSD, network share, etc.

**Comment by IncognitoTGT** [comment]
SD Card so local mount.

**Comment by IncognitoTGT** [comment]
Fixed. Added ` - ./db:/db/frigate` as a volume

**Comment by blakeblackshear** [comment]
I don't think that is correct. That is going to mount a folder called "frigate" next to your database file named "frigate.db". You want ` ./db:/db` based on your config.

**Comment by IncognitoTGT** [comment]
I actually did figure out that was the problem. Thanks.

**Comment by arne182** [comment]
I have also now tried this on a raspberry Pi 5 but am still getting that
Error importing detector runtime: /usr/local/lib/python3.9/dist-packages/openvino/pyopenvino.cpython-39-aarch64-linux-gnu.so: ELF load command alignment not page-aligned
Any other ideas of what is up here?

**Comment by arne182** [comment]
Without the CPU detector it will also not start recording. Could this have something to do with the coral TPU and the 64bit system?

**Comment by NickM-27** [comment]
did you mean to comment on this issue? the issue you are posting has nothing to do with this. Also nothing to do with coral

**Comment by arne182** [comment]
Error importing detector runtime: /usr/local/lib/python3.9/dist-packages/openvino/pyopenvino.cpython-39-aarch64-linux-gnu.so: ELF load command alignment not page-aligned is the same error I am getting and it has nothing to do with the DB but maybe @IncognitoTGT can check if the error is really gone and hopefully there is a solution in something that he tried.

**Comment by NickM-27** [comment]
You should make your own issue, again this won't actually stop anything from working
